apiVersion: networking.gke.io/v1beta1
kind: MultiClusterService
metadata:
  name: zone-svc
  annotations:
    beta.cloud.google.com/backend-config: '{"ports": {"80":"zone-health-check-cfg"}}'
spec:
  template:
    spec:
      selector:
        app: zoneprinter
      ports:
      - name: web
        protocol: TCP
        port: 80
        targetPort: 8080
